# Modeling

In [ ]:
from datetime import datetime
start_time = datetime.now()

#Libraries to load
!pip install lightgbm

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
import lightgbm as lgb
import numpy as np
%matplotlib inline

print('LOAD DURATION: ', datetime.now() - start_time) # load time about 30 seconds

In [14]:
%%time
vars = pd.read_csv('vars_final.csv')

Wall time: 587 ms

In [ ]:
df = pd.read_csv('vars1.csv')

In [18]:
abcd = vars.columns
abcd = list(abcd)
abcd

['address_count_30',
 'fulladdress_count_30',
 'fulladdress_count_7',
 'fulladdress_count_0_by_30',
 'fulladdressunique_count_fordob_homephone_60',
 'fulladdressunique_count_forssn_name_60',
 'fulladdressunique_count_forssn_60',
 'fulladdressunique_count_forssn_name_dob_60',
 'fulladdressunique_count_forname_dob_60',
 'fulladdressunique_count_forfulladdress_dob_60',
 'fulladdressunique_count_fordob_homephone_30',
 'fulladdressunique_count_forssn_name_fulladdress_30',
 'fulladdressunique_count_forssn_lastname_30',
 'fulladdressunique_count_forssn_zip5_30',
 'fulladdressunique_count_forssn_fulladdress_30',
 'fulladdressunique_count_forname_fulladdress_30',
 'fulladdressunique_count_forname_dob_30',
 'fulladdressunique_count_fordob_homephone_14',
 'fulladdressunique_count_forssn_lastname_14',
 'fulladdressunique_count_forname_dob_14',
 'fulladdressunique_count_fordob_homephone_7',
 'fulladdressunique_count_forssn_7',
 'fulladdressunique_count_forssn_name_fulladdress_7',
 'fulladdressunique_count_forname_fulladdress_7',
 'fulladdressunique_count_forname_dob_7',
 'fulladdressunique_count_forname_fulladdress_1',
 'ssn_dob_count_30',
 'lastname_dob_count_30',
 'firstname_dob_count_30',
 'ssn_count_30']

In [25]:
vars = df.loc[:,abcd]
vars.head()
vars.shape

(1000000, 30)

In [27]:
xyz = pd.read_csv('applications data.csv')

In [28]:
vars['record'] = xyz['record']

In [29]:
vars['Fraud'] = xyz['fraud_label']

In [30]:
vars.head()

,address_count_30,fulladdress_count_30,fulladdress_count_7,fulladdress_count_0_by_30,fulladdressunique_count_fordob_homephone_60,fulladdressunique_count_forssn_name_60,fulladdressunique_count_forssn_60,fulladdressunique_count_forssn_name_dob_60,fulladdressunique_count_forname_dob_60,fulladdressunique_count_forfulladdress_dob_60,...,fulladdressunique_count_forssn_name_fulladdress_7,fulladdressunique_count_forname_fulladdress_7,fulladdressunique_count_forname_dob_7,fulladdressunique_count_forname_fulladdress_1,ssn_dob_count_30,lastname_dob_count_30,firstname_dob_count_30,ssn_count_30,record,Fraud
0,1,1,1,30.0,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0
1,1,1,1,30.0,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,2,1
2,1,1,1,30.0,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,3,0
3,1,1,1,30.0,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,4,0
4,1,1,1,30.0,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,5,0

In [32]:
vars.shape

(1000000, 32)

In [33]:
# use this to cap variables. For some problems it helps
Clip = 10

In [34]:
vars['Fraud'].sum()

14393

In [35]:
vars.head(10)

,address_count_30,fulladdress_count_30,fulladdress_count_7,fulladdress_count_0_by_30,fulladdressunique_count_fordob_homephone_60,fulladdressunique_count_forssn_name_60,fulladdressunique_count_forssn_60,fulladdressunique_count_forssn_name_dob_60,fulladdressunique_count_forname_dob_60,fulladdressunique_count_forfulladdress_dob_60,...,fulladdressunique_count_forssn_name_fulladdress_7,fulladdressunique_count_forname_fulladdress_7,fulladdressunique_count_forname_dob_7,fulladdressunique_count_forname_fulladdress_1,ssn_dob_count_30,lastname_dob_count_30,firstname_dob_count_30,ssn_count_30,record,Fraud
0,1,1,1,30.0,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0
1,1,1,1,30.0,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,2,1
2,1,1,1,30.0,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,3,0
3,1,1,1,30.0,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,4,0
4,1,1,1,30.0,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,5,0
5,1,1,1,30.0,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,6,0
6,1,1,1,30.0,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,7,0
7,1,1,1,30.0,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,8,0
8,1,1,1,30.0,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,9,0
9,1,1,1,30.0,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,10,0

In [36]:
vars.shape

(1000000, 32)

In [44]:
vars.describe()

,address_count_30,fulladdress_count_30,fulladdress_count_7,fulladdress_count_0_by_30,fulladdressunique_count_fordob_homephone_60,fulladdressunique_count_forssn_name_60,fulladdressunique_count_forssn_60,fulladdressunique_count_forssn_name_dob_60,fulladdressunique_count_forname_dob_60,fulladdressunique_count_forfulladdress_dob_60,...,fulladdressunique_count_forssn_name_fulladdress_7,fulladdressunique_count_forname_fulladdress_7,fulladdressunique_count_forname_dob_7,fulladdressunique_count_forname_fulladdress_1,ssn_dob_count_30,lastname_dob_count_30,firstname_dob_count_30,ssn_count_30,record,Fraud
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,...,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,1.078171,1.064624,1.038997,29.491030,1.044485,1.038698,1.038559,1.043802,1.043294,1.043042,...,1.031745,1.031652,1.032356,1.022469,1.046097,1.049509,1.055134,1.050823,500000.500000,0.014393
std,0.664121,0.633831,0.581225,2.831175,0.617953,0.613817,0.613686,0.618063,0.617028,0.616503,...,0.574926,0.574846,0.575430,0.480685,0.496315,0.503405,0.517786,0.513331,288675.278933,0.119104
min,1.000000,1.000000,1.000000,1.304348,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,1.000000,1.000000,1.000000,30.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,250000.750000,0.000000
50%,1.000000,1.000000,1.000000,30.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,500000.500000,0.000000
75%,1.000000,1.000000,1.000000,30.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,750000.250000,0.000000
max,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,...,30.000000,30.000000,30.000000,30.000000,34.000000,34.000000,34.000000,34.000000,1000000.000000,1.000000

In [45]:
record_save = vars['record']
Y_save = pd.DataFrame(vars.loc[:,'Fraud'])
Y_save.head()

   Fraud
0      0
1      1
2      0
3      0
4      0

## Scale and truncate field values

In [46]:
X_no_scaling = vars.drop(columns = ['record','Fraud'])
X_no_scaling.describe()

,address_count_30,fulladdress_count_30,fulladdress_count_7,fulladdress_count_0_by_30,fulladdressunique_count_fordob_homephone_60,fulladdressunique_count_forssn_name_60,fulladdressunique_count_forssn_60,fulladdressunique_count_forssn_name_dob_60,fulladdressunique_count_forname_dob_60,fulladdressunique_count_forfulladdress_dob_60,...,fulladdressunique_count_fordob_homephone_7,fulladdressunique_count_forssn_7,fulladdressunique_count_forssn_name_fulladdress_7,fulladdressunique_count_forname_fulladdress_7,fulladdressunique_count_forname_dob_7,fulladdressunique_count_forname_fulladdress_1,ssn_dob_count_30,lastname_dob_count_30,firstname_dob_count_30,ssn_count_30
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,...,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,1.078171,1.064624,1.038997,29.491030,1.044485,1.038698,1.038559,1.043802,1.043294,1.043042,...,1.032526,1.031725,1.031745,1.031652,1.032356,1.022469,1.046097,1.049509,1.055134,1.050823
std,0.664121,0.633831,0.581225,2.831175,0.617953,0.613817,0.613686,0.618063,0.617028,0.616503,...,0.575568,0.574909,0.574926,0.574846,0.575430,0.480685,0.496315,0.503405,0.517786,0.513331
min,1.000000,1.000000,1.000000,1.304348,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,1.000000,1.000000,1.000000,30.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
50%,1.000000,1.000000,1.000000,30.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
75%,1.000000,1.000000,1.000000,30.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,...,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,34.000000,34.000000,34.000000,34.000000

In [47]:
X = (X_no_scaling - X_no_scaling.mean()) / X_no_scaling.std()

In [53]:
# push in any outlier values
cols = X.columns
X.loc[:,cols] = X[cols].clip(upper=Clip)
X.loc[:,cols] = X[cols].clip(lower=-1*Clip)
# X = (X_no_scaling - X_no_scaling.mean()) / X_no_scaling.std()
X.describe()
X

,address_count_30,fulladdress_count_30,fulladdress_count_7,fulladdress_count_0_by_30,fulladdressunique_count_fordob_homephone_60,fulladdressunique_count_forssn_name_60,fulladdressunique_count_forssn_60,fulladdressunique_count_forssn_name_dob_60,fulladdressunique_count_forname_dob_60,fulladdressunique_count_forfulladdress_dob_60,...,fulladdressunique_count_fordob_homephone_7,fulladdressunique_count_forssn_7,fulladdressunique_count_forssn_name_fulladdress_7,fulladdressunique_count_forname_fulladdress_7,fulladdressunique_count_forname_dob_7,fulladdressunique_count_forname_fulladdress_1,ssn_dob_count_30,lastname_dob_count_30,firstname_dob_count_30,ssn_count_30
0,-0.117706,-0.101958,-0.067094,0.179774,-0.071988,-0.063045,-0.062832,-0.07087,-0.070165,-0.069816,...,-0.056511,-0.055183,-0.055216,-0.055062,-0.056229,-0.046744,-0.092879,-0.098348,-0.10648,-0.099006
1,-0.117706,-0.101958,-0.067094,0.179774,-0.071988,-0.063045,-0.062832,-0.07087,-0.070165,-0.069816,...,-0.056511,-0.055183,-0.055216,-0.055062,-0.056229,-0.046744,-0.092879,-0.098348,-0.10648,-0.099006
2,-0.117706,-0.101958,-0.067094,0.179774,-0.071988,-0.063045,-0.062832,-0.07087,-0.070165,-0.069816,...,-0.056511,-0.055183,-0.055216,-0.055062,-0.056229,-0.046744,-0.092879,-0.098348,-0.10648,-0.099006
3,-0.117706,-0.101958,-0.067094,0.179774,-0.071988,-0.063045,-0.062832,-0.07087,-0.070165,-0.069816,...,-0.056511,-0.055183,-0.055216,-0.055062,-0.056229,-0.046744,-0.092879,-0.098348,-0.10648,-0.099006
4,-0.117706,-0.101958,-0.067094,0.179774,-0.071988,-0.063045,-0.062832,-0.07087,-0.070165,-0.069816,...,-0.056511,-0.055183,-0.055216,-0.055062,-0.056229,-0.046744,-0.092879,-0.098348,-0.10648,-0.099006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,-0.117706,-0.101958,-0.067094,0.179774,-0.071988,-0.063045,-0.062832,-0.07087,-0.070165,-0.069816,...,-0.056511,-0.055183,-0.055216,-0.055062,-0.056229,-0.046744,-0.092879,-0.098348,-0.10648,-0.099006
999996,-0.117706,-0.101958,-0.067094,0.179774,-0.071988,-0.063045,-0.062832,-0.07087,-0.070165,-0.069816,...,-0.056511,-0.055183,-0.055216,-0.055062,-0.056229,-0.046744,-0.092879,-0.098348,-0.10648,-0.099006
999997,-0.117706,-0.101958,-0.067094,0.179774,-0.071988,-0.063045,-0.062832,-0.07087,-0.070165,-0.069816,...,-0.056511,-0.055183,-0.055216,-0.055062,-0.056229,-0.046744,-0.092879,-0.098348,-0.10648,-0.099006
999998,-0.117706,-0.101958,-0.067094,0.179774,-0.071988,-0.063045,-0.062832,-0.07087,-0.070165,-0.069816,...,-0.056511,-0.055183,-0.055216,-0.055062,-0.056229,-0.046744,-0.092879,-0.098348,-0.10648,-0.099006
999999,-0.117706,-0.101958,-0.067094,0.179774,-0.071988,-0.063045,-0.062832,-0.07087,-0.070165,-0.069816,...,-0.056511,-0.055183,-0.055216,-0.055062,-0.056229,-0.046744,-0.092879,-0.098348,-0.10648,-0.099006

In [49]:
# separate data into modeling (traintest) and out of time
X_trntst = X[0:833507]
Y_trntst = Y_save[0:833507]
X_oot = X[833507:]
Y_oot = Y_save[833507:]

In [55]:
niter = 0
nitermax = 1
FDR3 = pd.DataFrame(np.zeros((nitermax,3)), columns=('trn', 'tst', 'oot'))
X_oot_orig = X_oot.copy()
pd.options.mode.chained_assignment = None  # default='warn'

In [56]:
%%time
# Logistic regression
params=[['liblinear', 'l1', 1],['lbfgs', 'l2', 1], ['lbfgs', 'l2',0.1], ['liblinear', 'l2', 1], ['lbfgs', 'l2',10]]
for i in range(0,5):
    for niter in range(nitermax): 
        X_trn, X_tst, Y_trn, Y_tst = train_test_split(X_trntst, Y_trntst, test_size = .3)

        model = LogisticRegression(solver=params[i][0], penalty=params[i][1], C=params[i][2])

        X_oot = X_oot_orig.copy()
        X_trn_save = X_trn.copy()
        Y_trn_save = Y_trn.copy()

        model.fit(X_trn, Y_trn.values.ravel())   

        predictions = model.predict_proba(X_trn_save)[:,1]
        X_trn['predicted'] = predictions
        X_trn['Fraud'] = Y_trn_save['Fraud']
        topRows = int(round(X_trn.shape[0]*0.03))
        temp = X_trn.sort_values('predicted',ascending=False).head(topRows)
        needed = temp.loc[:,'Fraud']
        FDR3.loc[niter, 'trn'] = sum(needed)/sum(X_trn.loc[:,'Fraud'])

        predictions = model.predict_proba(X_tst)[:,1]
        X_tst['predicted']=predictions
        X_tst['Fraud'] = Y_tst['Fraud']
        topRows = int(round(X_tst.shape[0]*0.03))
        temp = X_tst.sort_values('predicted',ascending=False).head(topRows)
        needed = temp.loc[:,'Fraud']
        FDR3.loc[niter, 'tst'] = sum(needed)/sum(X_tst.loc[:,'Fraud'])

        predictions = model.predict_proba(X_oot)[:,1]
        X_oot['predicted']=predictions
        X_oot['Fraud'] = Y_oot['Fraud']
        topRows = int(round(X_oot.shape[0]*0.03))
        temp = X_oot.sort_values('predicted',ascending=False).head(topRows)
        needed = temp.loc[:,'Fraud']
        FDR3.loc[niter, 'oot'] = sum(needed)/sum(X_oot.loc[:,'Fraud'])
        print(niter, FDR3.loc[niter, 'trn'],FDR3.loc[niter, 'tst'],FDR3.loc[niter, 'oot'])
    
    print(FDR3.mean())

0 0.49779420531775365 0.4919889502762431 0.48365465213746855
trn    0.497794
tst    0.491989
oot    0.483655
dtype: float64

C:\Users\saman\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0 0.4913885259532011 0.4930323299888517 0.4790444258172674
trn    0.491389
tst    0.493032
oot    0.479044
dtype: float64

C:\Users\saman\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0 0.4908070678127985 0.492150922610851 0.47778709136630343
trn    0.490807
tst    0.492151
oot    0.477787
dtype: float64
0 0.496701451361401 0.5057220708446867 0.4832355406538139
trn    0.496701
tst    0.505722
oot    0.483236
dtype: float64

C:\Users\saman\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0 0.5010069896931643 0.4952327537857543 0.4832355406538139
trn    0.501007
tst    0.495233
oot    0.483236
dtype: float64
Wall time: 2min 53s

## Models. You can comment out any of these cells and just explore one model type. You can also just rerun that single cell multiple times as you explore different model hyperparameters.

In [69]:
%%time
# Single DT
def1=[]
params1=[[10, 1, 2],[ 20 , 60 ,300], [20 , 60 , 320], [25,80,600]]

for i in range(0,4):
    for niter in range(nitermax):    
        X_trn, X_tst, Y_trn, Y_tst = train_test_split(X_trntst, Y_trntst, test_size = .3)

        model = DecisionTreeClassifier(max_depth=params1[i][0], min_samples_leaf=params1[i][1], min_samples_split=params1[i][2])

        X_oot = X_oot_orig.copy()
        X_trn_save = X_trn.copy()
        Y_trn_save = Y_trn.copy()

        model.fit(X_trn, Y_trn.values.ravel())   

        predictions = model.predict_proba(X_trn_save)[:,1]
        X_trn['predicted'] = predictions
        X_trn['Fraud'] = Y_trn_save['Fraud']
        topRows = int(round(X_trn.shape[0]*0.03))
        temp = X_trn.sort_values('predicted',ascending=False).head(topRows)
        needed = temp.loc[:,'Fraud']
        FDR3.loc[niter, 'trn'] = sum(needed)/sum(X_trn.loc[:,'Fraud'])

        predictions = model.predict_proba(X_tst)[:,1]
        X_tst['predicted']=predictions
        X_tst['Fraud'] = Y_tst['Fraud']
        topRows = int(round(X_tst.shape[0]*0.03))
        temp = X_tst.sort_values('predicted',ascending=False).head(topRows)
        needed = temp.loc[:,'Fraud']
        FDR3.loc[niter, 'tst'] = sum(needed)/sum(X_tst.loc[:,'Fraud'])

        predictions = model.predict_proba(X_oot)[:,1]
        X_oot['predicted']=predictions
        X_oot['Fraud'] = Y_oot['Fraud']
        topRows = int(round(X_oot.shape[0]*0.03))
        temp = X_oot.sort_values('predicted',ascending=False).head(topRows)
        needed = temp.loc[:,'Fraud']
        FDR3.loc[niter, 'oot'] = sum(needed)/sum(X_oot.loc[:,'Fraud'])
        def1.append([niter, FDR3.loc[niter, 'trn'],FDR3.loc[niter, 'tst'],FDR3.loc[niter, 'oot']])
        print(niter, FDR3.loc[niter, 'trn'],FDR3.loc[niter, 'tst'],FDR3.loc[niter, 'oot'])
    
print(params1, def1)

0 0.5229226361031518 0.5158358578903883 0.4953897736797988
0 0.5247571665482114 0.51164095371669 0.5020955574182733
0 0.5250565408879895 0.514420410427066 0.5008382229673093
0 0.5161831695037161 0.5339699863574352 0.49874266554903607
[[10, 1, 2], [20, 60, 300], [20, 60, 320], [25, 80, 600]] [[0, 0.5229226361031518, 0.5158358578903883, 0.4953897736797988], [0, 0.5247571665482114, 0.51164095371669, 0.5020955574182733], [0, 0.5250565408879895, 0.514420410427066, 0.5008382229673093], [0, 0.5161831695037161, 0.5339699863574352, 0.49874266554903607]]
Wall time: 5.34 s

In [71]:
%%time
# RF
def2 = []
params2 = [[100,10,5,1,2],[50,20,5,30,500],[50,20,5,30,300],[75,10,8,30,100]] 
for i in range(0,4):
    for niter in range(nitermax):    
        X_trn, X_tst, Y_trn, Y_tst = train_test_split(X_trntst, Y_trntst, test_size = .3)

        model = RandomForestClassifier(n_estimators=params2[i][0], max_depth=params2[i][1], max_features=params2[i][2], min_samples_leaf = params2[i][3], min_samples_split = params2[i][4])
        X_oot = X_oot_orig.copy()
        X_trn_save = X_trn.copy()
        Y_trn_save = Y_trn.copy()

        model.fit(X_trn, Y_trn.values.ravel())   

        predictions = model.predict_proba(X_trn_save)[:,1]
        X_trn['predicted'] = predictions
        X_trn['Fraud'] = Y_trn_save['Fraud']
        topRows = int(round(X_trn.shape[0]*0.03))
        temp = X_trn.sort_values('predicted',ascending=False).head(topRows)
        needed = temp.loc[:,'Fraud']
        FDR3.loc[niter, 'trn'] = sum(needed)/sum(X_trn.loc[:,'Fraud'])

        predictions = model.predict_proba(X_tst)[:,1]
        X_tst['predicted']=predictions
        X_tst['Fraud'] = Y_tst['Fraud']
        topRows = int(round(X_tst.shape[0]*0.03))
        temp = X_tst.sort_values('predicted',ascending=False).head(topRows)
        needed = temp.loc[:,'Fraud']
        FDR3.loc[niter, 'tst'] = sum(needed)/sum(X_tst.loc[:,'Fraud'])

        predictions = model.predict_proba(X_oot)[:,1]
        X_oot['predicted']=predictions
        X_oot['Fraud'] = Y_oot['Fraud']
        topRows = int(round(X_oot.shape[0]*0.03))
        temp = X_oot.sort_values('predicted',ascending=False).head(topRows)
        needed = temp.loc[:,'Fraud']
        FDR3.loc[niter, 'oot'] = sum(needed)/sum(X_oot.loc[:,'Fraud'])
        def2.append([niter, FDR3.loc[niter, 'trn'],FDR3.loc[niter, 'tst'],FDR3.loc[niter, 'oot']])
        print(niter, FDR3.loc[niter, 'trn'],FDR3.loc[niter, 'tst'],FDR3.loc[niter, 'oot'])

print(params1, def2)

0 0.522373773630055 0.5206906001644286 0.501257334450964
0 0.52029826014913 0.523327712197864 0.5020955574182733
0 0.5213393067672719 0.5157446808510638 0.5025146689019279
0 0.5244031518287663 0.5136986301369864 0.5008382229673093
[[10, 1, 2], [20, 60, 300], [20, 60, 320], [25, 80, 600]] [[0, 0.522373773630055, 0.5206906001644286, 0.501257334450964], [0, 0.52029826014913, 0.523327712197864, 0.5020955574182733], [0, 0.5213393067672719, 0.5157446808510638, 0.5025146689019279], [0, 0.5244031518287663, 0.5136986301369864, 0.5008382229673093]]
Wall time: 48.7 s

In [77]:
%%time
# BT
def3 = []
params3 = [[0.1,100,3,10],[0.01,800,5,30],[0.001,4000,4,30],[0.05,200,5,40]] 
for i in range(0,4):
    for niter in range(nitermax):    
        X_trn, X_tst, Y_trn, Y_tst = train_test_split(X_trntst, Y_trntst, test_size = .3)

        model = lgb.LGBMClassifier(learning_rate=params3[i][0], n_estimators=params3[i][1], max_depth=params3[i][2], num_leaves = params3[i][3])

        X_oot = X_oot_orig.copy()
        X_trn_save = X_trn.copy()
        Y_trn_save = Y_trn.copy()

        model.fit(X_trn, Y_trn.values.ravel())   

        predictions = model.predict_proba(X_trn_save)[:,1]
        X_trn['predicted'] = predictions
        X_trn['Fraud'] = Y_trn_save['Fraud']
        topRows = int(round(X_trn.shape[0]*0.03))
        temp = X_trn.sort_values('predicted',ascending=False).head(topRows)
        needed = temp.loc[:,'Fraud']
        FDR3.loc[niter, 'trn'] = sum(needed)/sum(X_trn.loc[:,'Fraud'])

        predictions = model.predict_proba(X_tst)[:,1]
        X_tst['predicted']=predictions
        X_tst['Fraud'] = Y_tst['Fraud']
        topRows = int(round(X_tst.shape[0]*0.03))
        temp = X_tst.sort_values('predicted',ascending=False).head(topRows)
        needed = temp.loc[:,'Fraud']
        FDR3.loc[niter, 'tst'] = sum(needed)/sum(X_tst.loc[:,'Fraud'])

        predictions = model.predict_proba(X_oot)[:,1]
        X_oot['predicted']=predictions
        X_oot['Fraud'] = Y_oot['Fraud']
        topRows = int(round(X_oot.shape[0]*0.03))
        temp = X_oot.sort_values('predicted',ascending=False).head(topRows)
        needed = temp.loc[:,'Fraud']
        FDR3.loc[niter, 'oot'] = sum(needed)/sum(X_oot.loc[:,'Fraud'])
        def3.append([niter, FDR3.loc[niter, 'trn'],FDR3.loc[niter, 'tst'],FDR3.loc[niter, 'oot']])
        print(niter, FDR3.loc[niter, 'trn'],FDR3.loc[niter, 'tst'],FDR3.loc[niter, 'oot'])
    
print(FDR3.mean(), def3)

0 0.5250706214689266 0.5126744517231558 0.5025146689019279
0 0.5206167084976694 0.5241758241758242 0.5025146689019279
0 0.5183736367946894 0.5205824698963876 0.49958088851634536
0 0.5195973949082298 0.5280741156653566 0.5033528918692373
trn    0.519597
tst    0.528074
oot    0.503353
dtype: float64 [[0, 0.5250706214689266, 0.5126744517231558, 0.5025146689019279], [0, 0.5206167084976694, 0.5241758241758242, 0.5025146689019279], [0, 0.5183736367946894, 0.5205824698963876, 0.49958088851634536], [0, 0.5195973949082298, 0.5280741156653566, 0.5033528918692373]]
Wall time: 35.2 s

In [81]:
%%time
# NN
def4 = []
params4 = [['relu',200,'constant',0.005,0.0001],['relu',500,'adaptive',0.01,0.0001],['logistic',100,'constant',0.001,0.001],['tanh',200,'invscaling',0.05,0.0003]] 
for i in range(0,4):
    
    for niter in range(nitermax):    
        X_trn, X_tst, Y_trn, Y_tst = train_test_split(X_trntst, Y_trntst, test_size = .3)

        model = MLPClassifier(activation=params4[i][0], max_iter=params4[i][1], learning_rate = params4[i][2], learning_rate_init = params4[i][3], alpha = params4[i][4])

        X_oot = X_oot_orig.copy()
        X_trn_save = X_trn.copy()
        Y_trn_save = Y_trn.copy()

        model.fit(X_trn, Y_trn.values.ravel())   

        predictions = model.predict_proba(X_trn_save)[:,1]
        X_trn['predicted'] = predictions
        X_trn['Fraud'] = Y_trn_save['Fraud']
        topRows = int(round(X_trn.shape[0]*0.03))
        temp = X_trn.sort_values('predicted',ascending=False).head(topRows)
        needed = temp.loc[:,'Fraud']
        FDR3.loc[niter, 'trn'] = sum(needed)/sum(X_trn.loc[:,'Fraud'])

        predictions = model.predict_proba(X_tst)[:,1]
        X_tst['predicted']=predictions
        X_tst['Fraud'] = Y_tst['Fraud']
        topRows = int(round(X_tst.shape[0]*0.03))
        temp = X_tst.sort_values('predicted',ascending=False).head(topRows)
        needed = temp.loc[:,'Fraud']
        FDR3.loc[niter, 'tst'] = sum(needed)/sum(X_tst.loc[:,'Fraud'])

        predictions = model.predict_proba(X_oot)[:,1]
        X_oot['predicted']=predictions
        X_oot['Fraud'] = Y_oot['Fraud']
        topRows = int(round(X_oot.shape[0]*0.03))
        temp = X_oot.sort_values('predicted',ascending=False).head(topRows)
        needed = temp.loc[:,'Fraud']
        FDR3.loc[niter, 'oot'] = sum(needed)/sum(X_oot.loc[:,'Fraud'])
        def4.append([niter, FDR3.loc[niter, 'trn'],FDR3.loc[niter, 'tst'],FDR3.loc[niter, 'oot']])    
        print(niter, FDR3.loc[niter, 'trn'],FDR3.loc[niter, 'tst'],FDR3.loc[niter, 'oot'])

print(FDR3.mean())

0 0.5234722055468843 0.5157694399129962 0.5004191114836547
0 0.5201751272038811 0.5208098987626547 0.49958088851634536
0 0.5190912334958963 0.5094444444444445 0.49874266554903607
0 0.5115732581365292 0.534324942791762 0.49832355406538137
trn    0.511573
tst    0.534325
oot    0.498324
dtype: float64
Wall time: 2min 56s

In [82]:
print('duration: ', datetime.now() - start_time)

duration:  4:35:31.346303